"""update item

Revision ID: 1741e90bf0de
Revises: 6bd4be4aafa5
Create Date: 2025-08-05 15:48:38.174592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1741e90bf0de'
down_revision: Union[str, Sequence[str], None] = '6bd4be4aafa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('items', 'owner_id')
    op.drop_column('items', 'is_active')
    op.drop_table('users')
    # ### end Alembic commands ###
